###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  ##########################################
  #              mariadb Image             #
  ##########################################

  mariadb:
    image: mariadb:10.4
    container_name: ShopApp-mariadb
    working_dir: /application
    volumes:
      - .:/application
      - my-data:/var/lib/mysql:rw
      # this will run all .sh, .sql and .sql.gz files found
      - ./Data:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=WeCreateApp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - "3307:3306"

  ##########################################
  #             webserver Image            #
  ##########################################

  webserver:
    image: nginx:alpine
    container_name: ShopApp-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  ##########################################
  #               php-fpm Image            #
  ##########################################
  php-fpm:
    build: phpdocker/php-fpm
    container_name: ShopApp-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  ##########################################
  #               maildev Image            #
  ##########################################
  #   https://github.com/maildev/maildev/issues/274#issuecomment-564542032
  #   http://127.0.1.1:1085/
  ##########################################
#
#  maildev:
#    image: maildev/maildev
#    container_name: ShopApp-maildev
#    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
#    ports:
#      - "1085:80"
#      - "1025:25"

volumes:
  my-data: